version: '3.1'

volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
  web:
    external: 
      name: web
  back-tier:

services:

  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    #ports:
    #  - 9090:9090
    links:
      - cadvisor:cadvisor
      - alertmanager:alertmanager
    depends_on:
      - cadvisor
    networks:
      - back-tier
    restart: always
#    deploy:
#      placement:
#        constraints:
#          - node.hostname == ${HOSTNAME}

  prometheus-proxy:
    image: jboss/keycloak-proxy:3.4.2.Final
    restart: always
    environment: 
      TARGET_URL: http://prometheus:9090
      HTTP_PORT: 8180
      HTTPS_PORT: 8443
      BASE_PATH: /
      REALM_NAME: REALNAME
      AUTH_SERVER_URL: https://login.example.com/auth
      CLIENT_ID: prometheus
      ROLE_ALLOWED: view
      SSL_REQUIRED: external
    volumes: 
      - ./keycloak-proxy/conf:/opt/jboss/conf
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:prometheus.smartpage.com.de
      - traefik.port=8180
    networks:
      - back-tier
      - web

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    #ports:
    #  - 9100:9100
    networks:
      - back-tier
    restart: always
    deploy:
      mode: global

  alertmanager:
    image: prom/alertmanager
    #ports:
    #  - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    networks:
      - back-tier
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
#    deploy:
#      placement:
#        constraints:
#          - node.hostname == ${HOSTNAME}
  alertmanager-proxy:
    image: jboss/keycloak-proxy:3.4.2.Final
    restart: always
    environment: 
      TARGET_URL: http://alertmanager:9093
      HTTP_PORT: 8180
      HTTPS_PORT: 8443
      BASE_PATH: /
      REALM_NAME: REALNAME
      AUTH_SERVER_URL: https://login.example.com/auth
      CLIENT_ID: prometheus
      ROLE_ALLOWED: alert
      SSL_REQUIRED: external
    volumes: 
      - ./keycloak-proxy/conf:/opt/jboss/conf
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:prometheus.smartpage.com.de
      - traefik.port=8180
    networks:
      - back-tier
      - web

  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    #ports:
    #  - 8080:8080
    networks:
      - back-tier
    restart: always
    deploy:
      mode: global
  cadvisor-proxy:
    image: jboss/keycloak-proxy:3.4.2.Final
    restart: always
    environment: 
      TARGET_URL: http://cadvisor:8080
      HTTP_PORT: 8180
      HTTPS_PORT: 8443
      BASE_PATH: /
      REALM_NAME: REALNAME
      AUTH_SERVER_URL: https://login.example.com/auth
      CLIENT_ID: cadvisor
      ROLE_ALLOWED: view
      SSL_REQUIRED: external
    volumes: 
      - ./keycloak-proxy/conf:/opt/jboss/conf
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:prometheus.smartpage.com.de
      - traefik.port=8180
    networks:
      - back-tier
      - web

  grafana:
    image: grafana/grafana
    user: "104"
    depends_on:
      - prometheus
    #ports:
    #  - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:graf.smartpage.com.de
      - traefik.port=3000
    networks:
      - back-tier
      - web
    restart: always

